# dictionary with the information to extract from the log files

history_dict:
    Jet flavour training loss: ["AvgLoss: ", ","]
    Jet flavour training accuracy: ["AvgAcc: ", "\n"]
    Combined training loss: ["AvgCombLoss: ", ","]
    Auxiliary training loss: ["AvgAuxLoss: ", ","]
    Origin training accuracy: ["AvgAuxAccPF: ", ","]
    VtxPos training MSE: ["AvgAuxDist: ", ","]
    SameVtx training accuracy: ["AvgAuxAccPair: ", "\n"]
    Jet flavour validation accuracy: ["validation metric: ", " ("]
    Jet flavour validation loss: ["validation loss: ", " ("]
    Combined validation loss: ["validation combined loss: ", " ("]
    Origin validation accuracy: ["validation aux metric PF: ", " ("]
    VtxPos validation MSE: ["validation aux distance: ", " ("]
    SameVtx validation accuracy: ["validation aux metric pair: ", " ("]
    Auxiliary validation loss: ["validation aux loss: ", " ("]
    # Jet flavour test accuracy: ["test metric: ", " ("]
    # Jet flavour test loss: ["test loss: ", " ("]
    # Combined test loss: ["test combined loss: ", " ("]
    # Origin test accuracy: ["test aux metric PF: ", " ("]
    # VtxPos test MSE: ["test aux distance: ", " ("]
    # SameVtx test accuracy: ["test aux metric pair: ", " ("]
    # Auxiliary test loss: ["test aux loss: ", " ("]
