# dictionary with the labels for the ROC curves
# first element in the list is the label for the signal
# second element in the list is the label for the background
# third element in the list is the label

ROC_TYPE_DICT:
    aux_labels:
        #0=b, 1=c, 2=bc, 3=other
        PF_SIP_b+bcVSc+other: [[0,2], [1,3], pf_clas]
        PF_b+bcVSc+other: [[0,2], [1,3], pf_clas]
        PF_VtxPos: [None, None, pf_regr]
        PAIR_SameVtx: [[0], None, pair_bin]
    primary_labels:
        #0=b, 1=bb, 4=uds, 5=g
        JET_bVSuds: [[0,1], [4], primary]
        JET_bVSg: [[0,1], [5], primary]
        JET_bVSudsg: [[0,1], [4,5], primary]


# dictionary with the extra features for the ROC curves
PF_EXTRA_FTS:
    PF_SIP_b+bcVSc+other : [pf_mask_charged, pf_var_IPsig]
    PF_b+bcVSc+other : [pf_mask_charged]
    PF_VtxPos : [pf_mask_from_b]
    #PF_VtxPos : [y_score_pf_clas]


# dictionary with the axes inf
AXIS_INF:
    PF_SIP_b+bcVSc+other: (0.4, 5e-3)
    PF_b+bcVSc+other:  (0.4, 5e-3)
    PF_comparison_b+bcVSc+other:  (0.4, 5e-3)
    PAIR_SameVtx:  (0.4, 1e-1)
    JET_bVSuds:  (0.5, 1e-4)
    JET_bVSg: (0.5, 1e-4)
    JET_bVSudsg: (0.5, 1e-4)


# dictionary with the axes limits
AXIS_LIMITS:
    0: ((30, 100),[[0,0.5],[0,3]], vtx_dist_pv, 3)
    1: ((200, 200),[[-0.06,0.06],[-0.06,0.06]], vtx_x, 0.2)
    2: ((200, 200),[[-0.06,0.06],[-0.06,0.06]], vtx_y, 0.2)
    3: ((200, 200),[[-3, 3],[-3,3]], vtx_z, 3)
